/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List files and folders
         * @description List files and folders in a directory at the specified path. The path should include the storage prefix; when omitted, the backend lists the default storage root.
         */
        get: operations["listFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload files
         * @description Upload one or more files to the specified directory. Uses multipart/form-data encoding. The file field name should be 'file'. The target path should be in 'path' field.
         */
        post: operations["uploadFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete files or folders
         * @description Delete one or more files or folders from the specified path.
         */
        post: operations["deleteFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rename a file or folder
         * @description Rename a file or folder to a new name.
         */
        post: operations["renameFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy files or folders
         * @description Copy one or more files or folders to a destination path.
         */
        post: operations["copyFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move files or folders
         * @description Move (cut) one or more files or folders to a destination path.
         */
        post: operations["moveFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a zip archive
         * @description Create a zip archive containing the specified files and folders.
         */
        post: operations["createArchive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract files from archive
         * @description Extract files and folders from a zip archive.
         */
        post: operations["extractArchive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create-file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new file
         * @description Create a new empty file at the specified path.
         */
        post: operations["createFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create-folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new folder
         * @description Create a new empty folder at the specified path.
         */
        post: operations["createFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get file preview
         * @description Get a preview of a file. Returns the file content directly. For text files, returns the text content. For images, returns the image. The response content-type should match the file's MIME type.
         */
        get: operations["previewFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a file
         * @description Get a download URL or trigger file download. Returns the file content with appropriate headers for download.
         */
        get: operations["downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search for files
         * @description Search for files and folders matching the specified criteria. Searches can be performed by filename, content, or other criteria depending on backend implementation.
         */
        get: operations["searchFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save content to file
         * @description Save text or binary content to a file at the specified path. Overwrites existing file if it already exists.
         */
        post: operations["saveFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DirEntry: {
            /**
             * @description Directory path containing this item
             * @example /documents
             */
            dir: string;
            /**
             * @description Base name of the file or folder
             * @example example.txt
             */
            basename: string;
            /**
             * @description File extension (empty string for folders)
             * @example txt
             */
            extension: string;
            /**
             * @description Full path to the item (including storage prefix, e.g., "local://documents/example.txt")
             * @example local://documents/example.txt
             */
            path: string;
            /**
             * @description Storage identifier
             * @example local
             */
            storage: string;
            /**
             * @description Item type - file or directory
             * @enum {string}
             */
            type: "file" | "dir";
            /**
             * @description File size in bytes (null for directories)
             * @example 1024
             */
            file_size?: number | null;
            /**
             * @description Last modified timestamp in seconds (Unix timestamp)
             * @example 1699123456
             */
            last_modified?: number | null;
            /**
             * @description MIME type of the file (null for directories)
             * @example text/plain
             */
            mime_type?: string | null;
            /**
             * @description Whether the item is read-only
             * @example false
             */
            read_only?: boolean;
            /**
             * @description Visibility status
             * @example public
             */
            visibility: string;
            /**
             * @description Optional preview URL for the file
             * @example https://api.example.com/api/files/preview?path=local://documents/example.txt
             */
            previewUrl?: string;
        };
        FsData: {
            /**
             * @description List of available storage identifiers
             * @example [
             *       "local"
             *     ]
             */
            storages: string[];
            /**
             * @description Current directory name/path
             * @example local://documents
             */
            dirname: string;
            /** @description List of files and folders in the directory */
            files: components["schemas"]["DirEntry"][];
            /**
             * @description Whether the current directory is read-only
             * @example false
             */
            read_only: boolean;
        };
        DeleteResult: components["schemas"]["FileOperationResult"] & {
            /** @description Optional list of successfully deleted items */
            deleted?: components["schemas"]["DirEntry"][];
        };
        FileOperationResult: {
            /** @description Updated file list after the operation */
            files: components["schemas"]["DirEntry"][];
            /**
             * @description Available storage identifiers
             * @example [
             *       "local"
             *     ]
             */
            storages: string[];
            /**
             * @description Whether the path is read-only
             * @example false
             */
            read_only: boolean;
            /**
             * @description Current directory name/path
             * @example local://documents
             */
            dirname: string;
        };
        FileContentResult: {
            /**
             * @description File content as text
             * @example Hello, World!
             */
            content: string;
            /**
             * @description MIME type of the content
             * @example text/plain
             */
            mimeType?: string;
        };
        DeleteRequest: {
            /**
             * @description Current directory path (including storage prefix)
             * @example local://uploads
             */
            path: string;
            items: {
                /**
                 * @description Full path to the item (including storage prefix)
                 * @example local://documents/file.txt
                 */
                path: string;
                /**
                 * @description Item type
                 * @enum {string}
                 */
                type: "file" | "dir";
            }[];
        };
        RenameRequest: {
            /**
             * @description Current directory path (including storage prefix)
             * @example local://uploads
             */
            path: string;
            /**
             * @description Current full path of the item to rename (including storage prefix)
             * @example local://documents/old-name.txt
             */
            item: string;
            /**
             * @description New name for the item
             * @example new-name.txt
             */
            name: string;
        };
        TransferRequest: {
            /**
             * @description Array of full paths to items to copy/move (including storage prefix)
             * @example [
             *       "local://documents/file1.txt",
             *       "local://documents/file2.txt"
             *     ]
             */
            sources: string[];
            /**
             * @description Full destination path (including storage prefix)
             * @example local://backup
             */
            destination: string;
            /**
             * @description Optional current directory path (including storage prefix), used to refresh the listing after the operation
             * @example local://uploads
             */
            path?: string;
        };
        ArchiveRequest: {
            /** @description Array of items to include in archive */
            items: {
                /** @description Full path to the item (including storage prefix) */
                path: string;
                /**
                 * @description Item type
                 * @enum {string}
                 */
                type: "file" | "dir";
            }[];
            /**
             * @description Directory path where archive should be created (including storage prefix)
             * @example local://documents
             */
            path: string;
            /**
             * @description Name for the archive file (typically .zip)
             * @example archive.zip
             */
            name: string;
        };
        UnarchiveRequest: {
            /**
             * @description Full path to the archive file to extract (including storage prefix)
             * @example local://documents/archive.zip
             */
            item: string;
            /**
             * @description Directory path where archive contents should be extracted (including storage prefix)
             * @example local://documents/extracted
             */
            path: string;
        };
        CreateItemRequest: {
            /**
             * @description Target directory path (including storage prefix)
             * @example local://uploads
             */
            path: string;
            /**
             * @description Name for the new item
             * @example new-file.txt
             */
            name: string;
        };
        SaveRequest: {
            /**
             * @description Full file path where content should be saved (including storage prefix)
             * @example local://uploads/file.txt
             */
            path: string;
            /**
             * @description Content to save (as string)
             * @example Hello, World!
             */
            content: string;
        };
        ErrorResponse: {
            /**
             * @description Error message
             * @example The specified path does not exist.
             */
            message: string;
            /**
             * @description Error code
             * @example path_not_found
             */
            code?: string;
            /**
             * @description Status flag (typically false for errors)
             * @example false
             */
            status?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listFiles: {
        parameters: {
            query?: {
                /**
                 * @description Directory path to list (including storage prefix, e.g., "local://uploads"). Defaults to the storage root when omitted.
                 * @example local://uploads
                 */
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved file list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "storages": [
                     *         "local"
                     *       ],
                     *       "dirname": "local://uploads",
                     *       "read_only": false,
                     *       "files": [
                     *         {
                     *           "dir": "local://uploads",
                     *           "basename": "file1.txt",
                     *           "extension": "txt",
                     *           "path": "local://uploads/file1.txt",
                     *           "storage": "local",
                     *           "type": "file",
                     *           "file_size": 1024,
                     *           "last_modified": 1699123456,
                     *           "mime_type": "text/plain",
                     *           "visibility": "public"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["FsData"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Path not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    uploadFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description File to upload
                     */
                    file: string;
                    /**
                     * @description Target directory path (including storage prefix)
                     * @example local://uploads
                     */
                    path: string;
                };
            };
        };
        responses: {
            /** @description Files uploaded successfully. Returns empty JSON response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {} */
                    "application/json": Record<string, never>;
                };
            };
            /** @description Bad request (invalid file, path, etc.) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden (read-only or insufficient permissions) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "path": "local://uploads",
                 *       "items": [
                 *         {
                 *           "path": "local://uploads/file.txt",
                 *           "type": "file"
                 *         },
                 *         {
                 *           "path": "local://uploads/folder",
                 *           "type": "dir"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["DeleteRequest"];
            };
        };
        responses: {
            /** @description Items deleted successfully. Returns updated file list (same format as list endpoint). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "storages": [
                     *         "local"
                     *       ],
                     *       "dirname": "local://uploads",
                     *       "read_only": false,
                     *       "files": [
                     *         {
                     *           "dir": "local://uploads",
                     *           "basename": "remaining-file.txt",
                     *           "extension": "txt",
                     *           "path": "local://uploads/remaining-file.txt",
                     *           "storage": "local",
                     *           "type": "file",
                     *           "file_size": 2048,
                     *           "last_modified": 1699123456,
                     *           "mime_type": "text/plain",
                     *           "visibility": "public"
                     *         }
                     *       ],
                     *       "deleted": [
                     *         {
                     *           "dir": "local://uploads",
                     *           "basename": "file.txt",
                     *           "extension": "txt",
                     *           "path": "local://uploads/file.txt",
                     *           "storage": "local",
                     *           "type": "file",
                     *           "file_size": 1024,
                     *           "last_modified": 1699123000,
                     *           "mime_type": "text/plain",
                     *           "visibility": "public"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden (read-only or insufficient permissions) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Items not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    renameFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "path": "local://uploads",
                 *       "item": "local://uploads/old-name.txt",
                 *       "name": "new-name.txt"
                 *     }
                 */
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description Item renamed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOperationResult"];
                };
            };
            /** @description Bad request (invalid name, conflict, etc.) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden (read-only or insufficient permissions) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    copyFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "path": "local://uploads",
                 *       "sources": [
                 *         "local://uploads/file1.txt",
                 *         "local://uploads/file2.txt"
                 *       ],
                 *       "destination": "local://backup"
                 *     }
                 */
                "application/json": components["schemas"]["TransferRequest"];
            };
        };
        responses: {
            /** @description Items copied successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOperationResult"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden (read-only or insufficient permissions) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Source items or destination not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    moveFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "path": "local://uploads",
                 *       "sources": [
                 *         "local://uploads/file.txt"
                 *       ],
                 *       "destination": "local://archive"
                 *     }
                 */
                "application/json": components["schemas"]["TransferRequest"];
            };
        };
        responses: {
            /** @description Items moved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOperationResult"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden (read-only or insufficient permissions) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Source items or destination not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createArchive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "path": "local://uploads",
                 *       "name": "my-archive.zip",
                 *       "items": [
                 *         {
                 *           "path": "local://uploads/file1.txt",
                 *           "type": "file"
                 *         },
                 *         {
                 *           "path": "local://uploads/folder",
                 *           "type": "dir"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ArchiveRequest"];
            };
        };
        responses: {
            /** @description Archive created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOperationResult"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden (read-only or insufficient permissions) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    extractArchive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "item": "local://uploads/archive.zip",
                 *       "path": "local://uploads/extracted"
                 *     }
                 */
                "application/json": components["schemas"]["UnarchiveRequest"];
            };
        };
        responses: {
            /** @description Archive extracted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOperationResult"];
                };
            };
            /** @description Bad request (invalid archive, corrupted, etc.) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden (read-only or insufficient permissions) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Archive not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "path": "local://uploads",
                 *       "name": "new-file.txt"
                 *     }
                 */
                "application/json": components["schemas"]["CreateItemRequest"];
            };
        };
        responses: {
            /** @description File created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOperationResult"];
                };
            };
            /** @description Bad request (file already exists, invalid name, etc.) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden (read-only or insufficient permissions) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "path": "local://uploads",
                 *       "name": "new-folder"
                 *     }
                 */
                "application/json": components["schemas"]["CreateItemRequest"];
            };
        };
        responses: {
            /** @description Folder created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOperationResult"];
                };
            };
            /** @description Bad request (folder already exists, invalid name, etc.) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden (read-only or insufficient permissions) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    previewFile: {
        parameters: {
            query: {
                /**
                 * @description Full path to the file (including storage prefix)
                 * @example local://uploads/image.jpg
                 */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File preview content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                    "image/jpeg": string;
                    "image/png": string;
                    "*/*": string;
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    downloadFile: {
        parameters: {
            query: {
                /**
                 * @description Full path to the file to download (including storage prefix)
                 * @example local://uploads/file.pdf
                 */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File download */
            200: {
                headers: {
                    /** @description Attachment header for file download */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                    "*/*": string;
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchFiles: {
        parameters: {
            query: {
                /**
                 * @description Base path to search within (including storage prefix)
                 * @example local://uploads
                 */
                path: string;
                /**
                 * @description Search query string (filename or content search, e.g., "*.pdf")
                 * @example *.pdf
                 */
                filter?: string;
                /**
                 * @description Search in subdirectories recursively
                 * @example true
                 */
                deep?: boolean;
                /**
                 * @description File size filter
                 * @example large
                 */
                size?: "all" | "small" | "medium" | "large";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "dirname": "local://uploads",
                     *       "storages": [
                     *         "local"
                     *       ],
                     *       "files": [
                     *         {
                     *           "dir": "local://uploads",
                     *           "basename": "document1.pdf",
                     *           "extension": "pdf",
                     *           "path": "local://uploads/document1.pdf",
                     *           "storage": "local",
                     *           "type": "file",
                     *           "file_size": 2048,
                     *           "last_modified": 1699123456,
                     *           "mime_type": "application/pdf",
                     *           "visibility": "public"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        /**
                         * @description Base search directory path
                         * @example local://uploads
                         */
                        dirname: string;
                        files: components["schemas"]["DirEntry"][];
                        /**
                         * @description Available storage identifiers
                         * @example [
                         *       "local"
                         *     ]
                         */
                        storages: string[];
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    saveFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "path": "local://uploads/file.txt",
                 *       "content": "Hello, World!\nThis is the file content."
                 *     }
                 */
                "application/json": components["schemas"]["SaveRequest"];
            };
        };
        responses: {
            /** @description File saved successfully. Returns file content as binary stream (same as preview endpoint). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                    "*/*": string;
                };
            };
            /** @description Bad request (invalid path, content, etc.) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden (read-only or insufficient permissions) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
